require:
  - rubocop-performance
  # - rubocop/require_tools
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  Exclude:
    - bin/**/*

  TargetRubyVersion: 2.5.3

Rails:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "scree.gemspec"

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/ClassLength:
  Max: 128

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 16

Metrics/PerceivedComplexity:
  Max: 8

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 10
